### Создать нового гостя
POST http://localhost:8000/api/guests
Content-Type: application/json

{
    "first_name": "kkkkkkk",
    "last_name": "kkkkkk",
    "phone": "+7779058518",
    "email": "kkkkkk.alex@example.com"
}

### Получить список гостей
GET http://localhost:8000/api/guests
Content-Type: application/json

### Получить гостя по ID
GET http://localhost:8000/api/guests/3
Content-Type: application/json

### Обновить гостя по ID
PUT http://localhost:8000/api/guests/3
Content-Type: application/json

{
    "first_name": "lal",
    "last_name": "lal",
    "phone": "+0987654325",
    "email": "lal.doe@example.com",
    "country": "Canada"
}

### Удалить гостя по ID
DELETE http://localhost:8000/api/guests/3
Content-Type: application/json
