### Создать нового гостя
POST http://localhost:8000/api/guests
Content-Type: application/json

{
    "first_name": "Alex",
    "last_name": "Don",
    "phone": "+7779058511",
    "email": "www.alex@example.com"
}

### Получить список гостей
GET http://localhost:8000/api/guests
Content-Type: application/json

### Получить гостя по ID
GET http://localhost:8000/api/guests/1
Content-Type: application/json

### Обновить гостя по ID
PUT http://localhost:8000/api/guests/1
Content-Type: application/json

{
    "first_name": "Jane",
    "last_name": "Doe",
    "phone": "+0987654321",
    "email": "jane.doe@example.com",
    "country": "Canada"
}

### Удалить гостя по ID
DELETE http://localhost:8000/api/guests/1
Content-Type: application/json
